name: TryPipeline
on:
  [push, workflow_dispatch]

jobs:
  apiRobotTest:
    name: Robot - api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install robot framework
          pip install robot framework-seleniumlibrary
          pip install robot framework-requests
      - name: Start Test
        run: |
          python -m robot -i api test/RobotFramework/tc.robot
